# the URL that references your upstream chart's tarball hosted in a Helm repository.
url: https://sumologic.github.io/sumologic-kubernetes-collection/sumologic-2.10.0.tgz
# The version of the package. This is used along with your upstream chart's name and version to generate a filename with the format {PACKAGE_NAME}-{VERSION}{packageVersion}.tgz for the package's tarball that gets generated.
packageVersion: 01